BiblioMit/Models/VM/Lib.cs
using System.Collections.Generic;

namespace BiblioMit.Models.VM
{
    public class LibManLibrary
    {
        public string Library { get; set; }
        public string Destination { get; set; }
        public List<string> Files { get; } = new List<string>();
        public string Provider { get; set; }
    }
}

BiblioMit/Models/VM/Libs.cs
using System.Collections.Generic;

namespace BiblioMit.Models.VM
{
    public class Libs
    {
        public string DefaultProvider { get; set; }
        public List<LibManLibrary> Libraries { get; } = new List<LibManLibrary>();
    }
}

BiblioMit/Models/VM/ModalVM/ModalFooter.cs
using System.ComponentModel.DataAnnotations;

namespace BiblioMit.Models
{
    public class ModalFooter
    {
        [Display(Name="Save")]
        public string SubmitButtonText { get; set; } = "Save";
        [Display(Name="Cancel")]
        public string CancelButtonText { get; set; } = "Cancel";
        public string SubmitButtonId { get; set; } = "btn-submit";
        public string CancelButtonId { get; set; } = "btn-cancel";
        public bool OnlyCancelButton { get; set; }
    }
}

BiblioMit/Models/VM/ModalVM/ModalHeader.cs
namespace BiblioMit.Models
{
    public class ModalHeader
    {
        public string Heading { get; set; }
    }
}

BiblioMit/Controllers/EntriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BiblioMit.Data;
using BiblioMit.Models;
using Microsoft.AspNetCore.Identity;
using BiblioMit.Services;
using Microsoft.AspNetCore.SignalR;
using Microsoft.Extensions.DependencyInjection;
using System.IO;
using OfficeOpenXml;
using BiblioMit.Extensions;
using Microsoft.AspNetCore.Http;
using System.Text;
using Microsoft.AspNetCore.Authorization;
using System.Globalization;

namespace BiblioMit.Controllers
{
    [Authorize]
    public class EntriesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<AppUser> _userManager;
        private readonly IServiceProvider _serviceProvider;
        private readonly IImport _import;
        public EntriesController(ApplicationDbContext context,
            IImport import,
            IServiceProvider serviceProvider,
            UserManager<AppUser> userManager)
        {
            _import = import;
            _context = context;
            _userManager = userManager;
            _serviceProvider = serviceProvider;
        }

        // GET: Entries
        public async Task<IActionResult> Index(int? id, int? pg, int? rpp, string srt,
            bool? asc, string[] val)
        {
            if (!pg.HasValue) pg = 1;
            if (!rpp.HasValue) rpp = 20;
            if (string.IsNullOrWhiteSpace(srt)) srt = "Date";
            if (!asc.HasValue) asc = false;

            var pre = _context.ProdEntry.Pre();
            var sort = _context.ProdEntry.FilterSort(srt);
            ViewData = _context.ProdEntry.ViewData(pre, pg, rpp, srt, asc, val);
            var Filters = ViewData["Filters"] as IDictionary<string, List<string>>;

            var applicationDbContext = asc.Value ?
                pre
                .OrderBy(x => sort.GetValue(x))
                .Skip((pg.Value - 1) * rpp.Value).Take(rpp.Value)
                .Include(e => e.AppUser) :
                pre
                .OrderByDescending(x => sort.GetValue(x))
                .Skip((pg.Value - 1) * rpp.Value).Take(rpp.Value)
                .Include(e => e.AppUser);

            ViewData["Processing"] = id;

            //if(Filters["Tipo"] == null || Filters["Tipo"].Count() == 0)
            //{
                Filters["Tipo"] = new List<string> { "Semilla", "Cosecha", "Abastecimiento", "Producción" };
            //}

            ViewData[nameof(Tipo)] = EViewData.Enum2Select<Tipo>(Filters, "Name");

            ViewData["Date"] = string.Format(CultureInfo.CurrentCulture, "'{0}'",
                string.Join("','", _context.ProdEntry.Select(v => v.Date.Date.ToString("yyyy-M-d", CultureInfo.CurrentCulture)).Distinct().ToList()));

            return View(await applicationDbContext.ToListAsync().ConfigureAwait(false));
        }

        // GET: Entries/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entry = await _context.ProdEntry
                .Include(e => e.AppUser)
                .SingleOrDefaultAsync(m => m.Id == id)
                .ConfigureAwait(false);
            if (entry == null)
            {
                return NotFound();
            }

            return View(entry);
        }

        [HttpGet]
        public IActionResult Output(int id)
        {
            var model = _context.ProdEntry.FirstOrDefault(e => e.Id == id);
            return PartialView("_Output", model);
        }

        // GET: Entries/Create
        [HttpGet]
        public IActionResult CreateFito()
        {
            return View();
        }

        [HttpPost]
        //[Produces("application/json")]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateFito(IFormFile qqfile)
        {
            if (qqfile == null) return Json(new { success = false, error = "error file null" });
            string error = null;

            if (qqfile.Length > 0)
            {
                var toskip = new List<string> { "Centre", "Fitoplanctons", "PSMB" };
                try
                {
                    using (var stream = new StreamReader(qqfile.OpenReadStream(), Encoding.GetEncoding("Windows-1252"), true))
                    {
                        var html = stream.ReadToEnd();
                        using (var temp = new TableToExcel())
                        {
                            temp.Process(html, out ExcelPackage xlsx);
                            //var package = new ExcelPackage(xlsx);
                            error = await _import.Fito(xlsx, toskip).ConfigureAwait(false);
                        }
                    }
                }
                catch (FileNotFoundException ex)
                {
                    return Json(new { success = false, error = ex.Message });
                }
            }
            return Json(new { success = string.IsNullOrWhiteSpace(error), error });
        }

        // GET: Entries/Create
        [HttpGet]
        public IActionResult Create()
        {
            var tipos = new Tipo[]
            {
                Tipo.Semilla,Tipo.Cosecha,Tipo.Abastecimiento,Tipo.Producción
            };

            ViewData[nameof(Tipo)] = new SelectList(
                            from Tipo s in tipos
                            select new
                            {
                                Id = (int)s,
                                Name = s.GetAttrName("es")
                            },
                            "Id", "Name");

            return View();
        }

        // POST: Entries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[RequestFormSizeLimit(valueCountLimit: 200000, Order = 1)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Excel,Reportes")] ProdEntry entry)
        {
            if (ModelState.IsValid)
            {
                if (entry?.Excel == null) return View(nameof(Create));

                entry.AppUserId = _userManager.GetUserId(User);
                entry.IP = Request.HttpContext.Connection.RemoteIpAddress.ToString();
                entry.FileName = entry.Excel.FileName;
                entry.Date = DateTime.Now;
                entry.Success = false;
                _context.Add(entry);
                await _context.SaveChangesAsync()
                    .ConfigureAwait(false);

                var result = string.Empty;

                //var debug = false;

                var toskip = new List<string> { "Row", "Sheet", "Centre", "Rows", "Id", "Origin" };

                if (entry.Reportes != Tipo.Producción)
                {
                    toskip.Add("TipoProduccion");
                    toskip.Add("Dato");
                    toskip.Add("TipoItemProduccion");
                }

                if (entry.Reportes != Tipo.Semilla)
                {
                    toskip.Add("OrigenId");
                    toskip.Add("Origen");
                }

                Stream stream = entry.Excel.OpenReadStream();
                ExcelPackage package = new ExcelPackage(stream);

                await _import.Read<Planilla>(package, entry, toskip).ConfigureAwait(false);

                return RedirectToAction(nameof(Index), new { id = entry.Id });
            }
            var Filters = new Dictionary<string, List<string>>
            {
                ["Tipo"] = new List<string> { "Semilla", "Cosecha", "Abastecimiento", "Producción" }
            };

            ViewData[nameof(Tipo)] = EViewData.Enum2Select<Tipo>(Filters, "Name");
            return View(entry);
        }

        // GET: Entries/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entry = await _context.ProdEntry.SingleOrDefaultAsync(m => m.Id == id)
                .ConfigureAwait(false);
            if (entry == null)
            {
                return NotFound();
            }
            ViewData["AppUserId"] = new SelectList(_context.AppUser, "Id", "Id", entry.AppUserId);
            return View(entry);
        }

        // POST: Entries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,AppUserId,IP,ProcessStart,ProcessTime,Stage,Reportes")] Entry entry)
        {
            if (id != entry?.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(entry);
                    await _context.SaveChangesAsync()
                        .ConfigureAwait(false);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EntryExists(entry.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AppUserId"] = new SelectList(_context.AppUser, "Id", "Id", entry.AppUserId);
            return View(entry);
        }

        // GET: Entries/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)

BiblioMit/Views/Shared/_ClearFilters.cshtml
@model string

<a class="btn btn-block btn-warning" title="Limpiar Filtros" href="@Model">
    <i class="fas fa-times fa-fw"></i><span class="d-none d-sm-inline">&nbsp;Limpiar Filtros</span>
</a>

BiblioMit/Views/Shared/_Dragndrop.cshtml
<partial name="_LibsPg" model='new HashSet<string> { "dragndrop" }' />

@if (ViewData["Error"] != null)
{
    @this.Block(@<script>
            $(document).ready(function () {
                alert('ERROR: @ViewData["Error"] Por favor verifique el formato del archivo y vuelva a intentarlo');
             })
    </script>, "Scripts")
}

BiblioMit/Views/Shared/_Favicons.cshtml
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="apple-mobile-web-app-title" content="BiblioMit">
<meta name="application-name" content="BiblioMit">
<meta name="theme-color" content="#ffffff">

BiblioMit/Views/Shared/_Filter.cshtml
@{ var Model = new BiblioMit.Models.ViewModels.FilterVM
    {
        Controller = (string)ViewData["controller"],
        Action = (string)ViewData["action"],
        Srt = (string)ViewData["srt"],
        Asc = (bool)ViewData["asc"],
        Rpp = (int)ViewData["rpp"]
    };
    Model.Val.AddRange((string[])ViewData["val"]);
}

@this.Block(@<script>
    function filter(v) {
        var tag = v.tagName;
        var val = "@string.Join(",",Model.Val)"
        var url = '@Html.Raw(Url.Action(Model.Action, Model.Controller,
                    new {
                        rpp = Model.Rpp,
                        srt = "SRT",
                        asc = Model.Asc,
                        val = "JSVAL"
                    }))';
        var name = $(v).attr('id');
        if (tag === "DIV") {
            url = url.replace("SRT", name);
            url = url.replace("JSVAL", val);
        } else {
            url = url.replace("SRT", "@Model.Srt");
            var obj = {};
            if (val !== "") {
                var filters = val.split(';');
                filters.forEach(function (filter) {
                    var pair = filter.split(':');
                    obj[pair[0]] = pair[1];
                });
            }
            console.log(val);
            if (tag === "INPUT") {
                if ($(v).attr("type") === "checkbox") {
                    obj[name] = $(v)[0].value;
                } else if ($(v).hasClass('hasDatepicker')) {
                    obj[name] = $(v)[0].value;
                    //url = url.replace("JSVAL", $(v)[0].value);
                } else {
                    obj[name] = $(v).value;
                    //url = url.replace("JSVAL", name + ":" + $(v).value);
                }
            } else if (tag === "SELECT") {
                obj[name] = $(v).find(":selected").map(function () { return this.value }).get().join(',');
                //url = url.replace("JSVAL", $(v).find(":selected").map(function () { return this.value }).get().join(","));
            }
            var out = [];
            $.each(obj, function (index, value) {
                out.push(index + ':' + value);
            });
            url = url.replace("JSVAL",out.join(';'));
        }
        window.location.href = url;
    }
</script>, "Scripts")

BiblioMit/Views/Shared/_FineUploader.cshtml
<partial name="_LibsPg" model='new HashSet<string> { "fine-uploader" }' />

@this.Block(@<script type="text/template" id="qq-template-manual-trigger">
                 <div class="qq-uploader-selector qq-uploader" qq-drop-area-text="Arroje archivos aquí">
                     <div class="qq-total-progress-bar-container-selector qq-total-progress-bar-container">
                         <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"
                              class="qq-total-progress-bar-selector qq-progress-bar qq-total-progress-bar"></div>
                     </div>
                     <div class="qq-upload-drop-area-selector qq-upload-drop-area" qq-hide-dropzone>
                         <span class="qq-upload-drop-area-text-selector"></span>
                     </div>
                     <div class="buttons">
                         <div class="qq-upload-button-selector qq-upload-button w-50">
                             <div>Buscar archivos</div>
                         </div>
                         <button type="button" id="trigger-upload" class="btn btn-primary">
                             <i class="icon-upload icon-white"></i> Subir
                         </button>
                     </div>
                     <span class="qq-drop-processing-selector qq-drop-processing">
                         <span>Procesando archivos...</span>
                         <span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span>
                     </span>
                     <ul class="qq-upload-list-selector qq-upload-list" aria-live="polite" aria-relevant="additions removals">
                         <li>
                             <div class="qq-progress-bar-container-selector">
                                 <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-progress-bar-selector qq-progress-bar"></div>
                             </div>
                             <span class="qq-upload-spinner-selector qq-upload-spinner"></span>
                             <img class="qq-thumbnail-selector" qq-max-size="100" qq-server-scale>
                             <span class="qq-upload-file-selector qq-upload-file"></span>
                             <span class="qq-edit-filename-icon-selector qq-edit-filename-icon" aria-label="Editar nombre de archivo"></span>
                             <input class="qq-edit-filename-selector qq-edit-filename" tabindex="0" type="text">
                             <span class="qq-upload-size-selector qq-upload-size"></span>
                             <button type="button" class="qq-btn qq-upload-cancel-selector qq-upload-cancel">Cancelar</button>
                             <button type="button" class="qq-btn qq-upload-retry-selector qq-upload-retry">Reintentar</button>
                             <button type="button" class="qq-btn qq-upload-delete-selector qq-upload-delete">Eliminar</button>
                             <span role="status" class="qq-upload-status-text-selector qq-upload-status-text"></span>
                         </li>
                     </ul>
                     <dialog class="qq-alert-dialog-selector">
                         <div class="qq-dialog-message-selector"></div>
                         <div class="qq-dialog-buttons">
                             <button type="button" class="qq-cancel-button-selector">Cerrar</button>
                         </div>
                     </dialog>

                     <dialog class="qq-confirm-dialog-selector">
                         <div class="qq-dialog-message-selector"></div>
                         <div class="qq-dialog-buttons">
                             <button type="button" class="qq-cancel-button-selector">No</button>
                             <button type="button" class="qq-ok-button-selector">Si</button>
                         </div>
                     </dialog>

                     <dialog class="qq-prompt-dialog-selector">
                         <div class="qq-dialog-message-selector"></div>
                         <input type="text">
                         <div class="qq-dialog-buttons">
                             <button type="button" class="qq-cancel-button-selector">Cancelar</button>
                             <button type="button" class="qq-ok-button-selector">Ok</button>
                         </div>
                     </dialog>
                 </div>
    </script>, "Styles")
@this.Block(@<style>
    .qq-upload-list{
        max-height:400px;
    }
    #trigger-upload {
        color: white;
        background-color: #00ABC7;
        font-size: 14px;
        padding: 7px 20px;
        background-image: none;
    }
    #fine-uploader-manual-trigger .qq-upload-button {
        margin-right: 15px;
    }
    #fine-uploader-manual-trigger .buttons {
        width: 36%;
    }
    #fine-uploader-manual-trigger .qq-uploader .qq-total-progress-bar-container {
        width: 60%;
    }
</style>, "Styles")
<div id="fine-uploader-manual-trigger"></div>
@this.Block(
@<script>
        var token = $('input:hidden[name="__RequestVerificationToken"]').val();
        var manualUploader = new qq.FineUploader({
            element: document.getElementById('fine-uploader-manual-trigger'),
            template: 'qq-template-manual-trigger',
            request: {
                endpoint: '@Url.Action("CreateFito","Entries")',
                //customHeaders: {
                //    'X-CSRF-TOKEN': token,
                //    'X-CSRFToken': token
                //},  // for token validation
                params: {
                    pid: 1,
                    aid: 1
                    //'csrfmiddlewaretoken': token
                }  // any custom params about file
            },
            thumbnails: {
                placeholders: {
                    waitingPath: '/lib/fine-uploader/fine-uploader/placeholders/waiting-generic.png',
                    notAvailablePath: '/images/thumbs/excel.png'
                }
            },
            autoUpload: false,
            debug: true,
            form: {
                element: "upload"
            },
            validation: {
                allowedExtensions: ['xls'],
                itemLimit: 10000,
                sizeLimit: 20971520
            },
            failedUploadTextDisplay: {
                mode: 'custom' 
            },
            text: {
                // localize text, for example - RUSSIAN (comment this for english)
                paused: 'pausado',
                failUpload:'Falló la subida',
                defaultResponseError: 'Error de carga por motivo desconocido',
                formatProgress: '{percent}% de {total_size}',
                waitingForResponse: 'Procesando...'
            },
            messages: {
                // localize text, for example - RUSSIAN (comment this for english)
                //tooManyItemsError: "Too many items ({netItems}) would be uploaded.  Item limit is {itemLimit}.",
                tooManyFilesError: 'Demasiados archivos ({netItems}), el límite son {itemLimit}.',
                unsupportedBrowser: 'Error irrecuperable - el navegador no permite la carga de archivos',
                emptyError: '{file} está vacio',
                noFilesError: 'Sin archivos para subir',
                onLeave:'Los archivos están siendo cargados, ¿quiere cancelar la carga de archivos?'
            },
            retry: {
                autoRetryNote: 'Reintentado {retryNum}/{maxAuto}'
            },
            showMessage: message => $('#MessageUploaderError').html(message),
            callbacks: {
                onSubmit: (id, name) => console.log("in onSubmit: " + id + " | " + name),
            }
        });

    qq(document.getElementById("trigger-upload")).attach("click", function () {
        manualUploader.uploadStoredFiles();
    });
</script>, "Scripts")

BiblioMit/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="@Localizer["en"]">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <title>@ViewData["Title"] - BiblioMit</title>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-46146363-2');
    </script>
    <script>
        window['GoogleAnalyticsObject'] = 'ga';
        window['ga'] = window['ga'] || function () {
            (window['ga'].q = window['ga'].q || []).push(arguments)
        };
    </script>
    <meta name="author" content="Epic Solutions" />
    <open-graph-website site-name="BiblioMit"
                        title="@ViewData["Title"]"
                        main-image="@(new OpenGraphImage(
        new Uri($"{Context.Request.Scheme}://{Context.Request.Host}/android-chrome-512x512.png"),
        "image/png",
        1200,
        630))"
                        determiner="@OpenGraphDeterminer.Blank" />
    <script type="application/ld+json">
        @{
            var website = new WebSite()
            {
                AlternateName = "Biblioteca y repositorio digital de Mytilus chilensis",
                Name = "BiblioMit - " + (string)ViewData["Title"],
                Url = new Uri($"{Context.Request.Scheme}://{Context.Request.Host}{Context.Request.Path}{Context.Request.QueryString}")
            };
            var jsonLd = website.ToString();
        }
        @Html.Raw(jsonLd)
    </script>
    @Html.Raw(new TwitterCardSummaryLargeImage
{
    Title = "BiblioMit",
    Description = "Biblioteca y repositorio digital de Mytilus chilensis",
    CreatorUsername = "@guille_arp",
    SiteUsername = "@guille_arp"
})
    <!-- Google Tag Manager -->
    @*<script src="~/js/google-ads.js"></script>*@
    <environment exclude="Development">
        <script>
            (function (w, d, s, l, i) {
                w[l] = w[l] || []; w[l].push({
                    'gtm.start':
                        new Date().getTime(), event: 'gtm.js'
                }); var f = d.getElementsByTagName(s)[0],
                    j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
                        'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
            })(window, document, 'script', 'dataLayer', 'GTM-W7K9PRH');</script>
        <!-- End Google Tag Manager -->
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-46146363-2"></script>
        @*<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>*@
        @*<script src="~/js/google-ads.min.js" asp-append-version="true"></script>*@
        <meta name="google-site-verification" content="g-pGvrm_POLRtvTDGYJTTkKtecLY11qo0zOeNVMY2Eg" />
    </environment>
    <partial name="_Favicons" />
    <partial name="_Libs" model='(new HashSet<string> { "jquery", "bootstrap", "@fortawesome/fontawesome-free", "site", "modal-action" }, "TOP")' />
    @this.WriteBlocks("TOPStyles")
    @this.WriteBlocks("Styles")
    @RenderSection("Styles", required: false)
</head>
<body>
    <!-- Google Tag Manager (noscript) -->
    <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-W7K9PRH"
                height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <!-- End Google Tag Manager (noscript) -->
    <header>
        <div class="fixed-top">
            <partial name="_Nav" />
            @RenderSection("NavBar", required: false)
        </div>
    </header>
    <main role="main">
        <div class="body-content container-fluid">
            <partial name="_CookieConsentPartial" />
            <!-- Load Facebook SDK for JavaScript -->
            <div id="fb-root"></div>
            <script>
                window.fbAsyncInit = function () {
                    FB.init({
                        xfbml: true,
                        version: 'v5.0'
                    });
                };

                (function (d, s, id) {
                    var js, fjs = d.getElementsByTagName(s)[0];
                    if (d.getElementById(id)) return;
                    js = d.createElement(s); js.id = id;
                    js.src = 'https://connect.facebook.net/es_LA/sdk/xfbml.customerchat.js';
                    fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));</script>

            <!-- Your customer chat code -->
            <div class="fb-customerchat"
                 attribution=setup_tool
                 page_id="1350128371792150"
                 theme_color="#20cef5"
                 logged_in_greeting="¡Hola! ¿Cómo podemos ayudarte?"
                 logged_out_greeting="¡Hola! ¿Cómo podemos ayudarte?">
            </div>
            @RenderBody()
            <partial name="_Modal" model='new BootstrapModel { Id = "modal-action", AreaLabeledId = "modal-action-label", Size = ModalSize.Medium }' />
        </div>
    </main>
    <footer class="container-fluid">
        <div class="row justify-content-between">
            <div class="col-md-3">
                <p>
                    <a asp-controller="Home" asp-action="Manual">
                        <i class="fas fa-info-circle fa-tw"></i> @Localizer["User Manual"]
                    </a>
                </p>
            </div>
            <div class="col-md-4 align-self-end">
                <div class="row">
                    <div class="col">
                        <a target="_blank" href="https://www.epicsolutions.cl">
                            <img src="~/epic_light_hor.svg" alt="epic solutions" class="img-responsive" height="20" />
                        </a>
                    </div>
                    <div class="col">
                        <p class="text-right">
                            &copy; @DateTime.Now.Year - BiblioMit
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    @this.WriteBlocks("TOPScripts")
    @RenderSection("ScripTop", required: false)
    @this.WriteBlocks("Scripts")
    @RenderSection("Scripts", required: false)
</body>
</html>

BiblioMit/Views/Shared/_LibsPg.cshtml
@model HashSet<string>

@{ 
    var pageName = ViewContext.RouteData.Values.ContainsKey("action") ?
        ViewContext.RouteData.Values["action"].ToString() :
        ViewContext.RouteData.Values.ContainsKey("page") ?
        ViewContext.RouteData.Values["page"].ToString().Split("/").Last() :
        null;
    Model.Add(pageName.Substring(0, 1).ToLowerInvariant() + pageName.Substring(1));
}

<partial name="_Libs" model='(Model, "")' />

BiblioMit/Views/Shared/_LibsPg0.cshtml
@{
    var model = new HashSet<string>();
}
<partial name="_LibsPg" model='model' />

BiblioMit/Views/Shared/_ModalHeader.cshtml
@model BiblioMit.Models.ModalHeader

<div class="modal-header">
    <h4 class="modal-title">@Model.Heading</h4>
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
</div>

BiblioMit/Views/Shared/_NavDDwn.cshtml
@model BiblioMit.Models.VM.NavVM.NavDDwnVM
@{ var first = true; }
@*asp-controller="@Model.Controller" asp-action="@Model.Action"*@
@*data-toggle="@item[4]" data-target="@item[5]"*@
<li class="nav-item dropdown">
    <button class="nav-link dropdown-toggle btn btn-dark"
            id="@Model.Action" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
        <figure class="text-center">
            <i class="fas fa-@Model.Logo fa-tw logo @Model.Logo"></i>
            <figcaption class="light-caption">@Model.Title</figcaption>
        </figure>
    </button>
    <div class="dropdown-menu" aria-labelledby="@Model.Action">
        @foreach (var section in Model.Sections)
        {
            <div class="dropdown-header">@Localizer[section.Key]:</div>
            @foreach (var item in section.Value)
            {
                <a class="dropdown-item"
                   asp-controller="@item[0]" asp-action="@item[1]">
                    <i class="@item[3] fa-tw"></i>&emsp;@item[2]
                </a>
            }
            if (!first)
            {
                <div class="dropdown-divider"></div>
            }
            else
            {
                first = false;
            }
        }
    </div>
</li>